/* 
PRIMARY KEY — PostgreSQL

Definition:
A Primary Key is a column or combination of columns used to uniquely identify each row in a table.

Key Points:
• Must contain unique values.
• Cannot contain NULL values.
• A table can have only one Primary Key.
• A Primary Key can contain one or multiple columns.
• Multiple columns together form a Composite Primary Key.
• It helps maintain data integrity by preventing duplicate records.

Example:
In a Students table, student_id can be a Primary Key because each student has a unique ID.

Remember:
Primary Key = UNIQUE + NOT NULL + Identifies each row
*/
-- FOR SETTING THE PRIMARY KEY TO START FROM PARTICULAR NUMBER USE:
-- id INT GENERATED BY DEFAULT AS IDENTITY(START WITH ur_number) PRIMARY KRY

DROP TABLE IF EXISTS basics.sales;
CREATE TABLE basics.sales(
    id INT GENERATED BY DEFAULT AS IDENTITY (START WITH 10) PRIMARY KEY ,

     title TEXT NOT NULL,
    
     price NUMERIC(10,2) NOT NULL DEFAULT 0,
     created_at TIMESTAMP DEFAULT NOW()

);

INSERT INTO basics.sales(title, price)
VALUES
('sales 1', 2001),
('sales 2', 2051);

SELECT * FROM basics.sales ;